### PR TITLE
Fix intro of msgpack package contents

### PR DESCRIPTION
**Pull request by shamaton**
Currently, this website fails about generating intro of github.com package contents.
I fixed this problem.

please see the belows.

Current version
image

Fixed version
image

### CODE REVIEW

**Comment by shamaton** [comment]
@frsyuki Could you review this PR?

**Comment by shamaton** [comment]
@kzk  Could you review this PR?

**Comment by shamaton** [comment]
@repeatedly Could you review this PR?

**Comment by o-alexandrov** [comment]
@gfx could you please let us know who would be able to approve the PR or, maybe, could you? As you are very active in [msgpack-javascript](https://github.com/msgpack/msgpack-javascript), I thought you might help

**Comment by frsyuki** [comment]
Merged. Thank you!

**Pull request merged**
